spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attrade?serverTimezone=UTC
    username: root
    password: root
#spring.jpa.hibernate.ddl-auto=update
#instead above
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: validate
# for new resolver (doesn't need for thymeleaf)
  freemarker:
    expose-request-attributes: true
    cache: false
#mail
  mail:
      host: smtp.gmail.com
      username: mgsvirydclone@gmail.com
      password: mikhail2000
      port: 587
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#session
  session:
      jdbc:
        initialize-schema: always
        table-name: SPRING_SESSION

#profiles
  profiles:
      active: ${devMode}

  main:
          allow-bean-definition-overriding: true

# server path
server:
  path:
    absolute: d:\java\projects\attrade-core
    upload: \upload
    picture: \upload\picture


mail:
  debug: true

#recapcha
recaptcha:
  secret: 6LcO9rUUAAAAAICFX3nGx8UBOGWyq_WmJ53Pl1qL
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

#info
info:
  url: http://localhost:8080
  logo: Attrade

#webpack
webpack:
  devPort: http://localhost:8000

#registration
registration:
  token:
    expirationDT: 5M
  validation:
    password:
      regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z0-9_-]{8,}$'
      message: 'Мин 8 символов(латинские буквы, цифры): мин 1 цифра, мин 1 прописная'

#logging
logging:
  level:
    by:
      attrade:
        controller: DEBUG
        config: DEBUG
        service: DEBUG

#jsoup
jsoup:
  userAgent: Chrome/4.0.249.0 Safari/532.5
  referrer: http://www.google.com
  s3:
    ru:
      product:
        nameParent: .catalog-element
        nameChild: .header
        codeParent: table#catalog_element
        codeChild: .gray
        codeIndexElement: 0
        supplierCodeParent: table#catalog_element
        supplierCodeChild: .gray
        supplierCodeIndexElement: 1
        categoriesParent: .breadcrumb-navigation
        categoriesChild: li
        categoriesStartWithIndex: 2
        filtersParent: .table-hover
        filtersChild: td
        imageParent: .big_image
        imageChild: img

#TODO
product:
  search:
    sortFieldsNames:
                - visitors
    sortFieldsTypes:
                - int
    sortReverse:
                - true
    minGramSize: 3
    onFields:
                - name
                - code
                - category.name

#https://console.cloud.google.com/apis/credentials?project=attrade-core&supportedpurview=project
facebook:
    client:
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        clientId: 233668646673605
        clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
        tokenName: oauth_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
    resource:
        userInfoUri: https://graph.facebook.com/me
github:
    client:
        accessTokenUri: https://github.com/login/oauth/access_token
        clientAuthenticationScheme: form
        clientId: bd1c0a783ccdd1c9b9e4
        clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
        userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
        userInfoUri: https://graph.github.com/me
google:
    client:
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        clientAuthenticationScheme: form
        clientId: 185460716091-1rasqe3vdl56flepchpugq569c4hasnk.apps.googleusercontent.com
        clientSecret: ${clientSecret}
        scope: openid,email,profile
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
        preferTokenInfo: true
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
security:
    oauth2:
        client:
            auto-approve-scopes: '''.*'''
            client-id: acme
            client-secret: acmesecret
            scope: read,write

