spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attrade?serverTimezone=UTC
    username: root
    password: root
#spring.jpa.hibernate.ddl-auto=update
#instead above
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: validate
# for new resolver (doesn't need for thymeleaf)
  freemarker:
    expose-request-attributes: true
    cache: false
#mail
  mail:
      host: smtp.gmail.com
      username: mgsvirydclone@gmail.com
      password: mikhail2000
      port: 587
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#session
  session:
      jdbc:
        initialize-schema: always
        table-name: SPRING_SESSION

#profiles
  profiles:
      active: ${devMode}

# server path
server:
  path:
    absolute: d:\java\projects\attrade-core
    upload: \upload
    picture: \upload\picture


mail:
  debug: true

#recapcha
recaptcha:
  secret: 6LcO9rUUAAAAAICFX3nGx8UBOGWyq_WmJ53Pl1qL
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

#info
info:
  url: http://localhost:8080
  logo: Attrade

#webpack
webpack:
  devPort: http://localhost:8000

#registration
registration:
  token:
    expirationDT: 5M
  validation:
    password:
      regex: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z0-9_-]{8,}$'
      message: 'Мин 8 символов(латинские буквы, цифры): мин 1 цифра, мин 1 прописная'

#logging
logging:
  level:
    by:
      attrade:
        controller: DEBUG
        config: DEBUG
        service: DEBUG

#jsoup
jsoup:
  userAgent: Chrome/4.0.249.0 Safari/532.5
  referrer: http://www.google.com
  s3:
    ru:
      product:
        nameParent: .catalog-element
        nameChild: .header
        codeParent: table#catalog_element
        codeChild: .gray
        codeIndexElement: 0
        supplierCodeParent: table#catalog_element
        supplierCodeChild: .gray
        supplierCodeIndexElement: 1
        categoriesParent: .breadcrumb-navigation
        categoriesChild: li
        categoriesStartWithIndex: 2
        filtersParent: .table-hover
        filtersChild: td
        imageParent: .big_image
        imageChild: img

#TODO
product:
  search:
    sortFieldsNames:
                - visitors
    sortFieldsTypes:
                - int
    sortReverse:
                - true
    minGramSize: 3
    onFields:
                - name
                - code
                - category.name
