spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attrade?serverTimezone=UTC
    username: root
    password: root
#spring.jpa.hibernate.ddl-auto=update
#instead above
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate.ddl-auto: validate

  freemarker:
    expose-request-attributes: true
    cache: false
#mail
  mail:
      host: smtp.gmail.com
      username: mgsvirydclone@gmail.com
      password: mikhail2000
      port: 587
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
#session
  session:
      jdbc:
        initialize-schema: always
        table-name: SPRING_SESSION

#profiles
  profiles:
      active: ${devMode}

  main:
          allow-bean-definition-overriding: true


# server path
server:
  language: en
  path:
    absolute: d:\java\projects\attrade-core
    upload: \upload
    picture: \upload\picture


mail:
  debug: true

#recapcha
recaptcha:
  secret: 6LcO9rUUAAAAAICFX3nGx8UBOGWyq_WmJ53Pl1qL
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

#info
info:
  url: http://localhost:8080
  logo: Attrade

#webpack
webpack:
  devPort: http://localhost:8000

#registration
registration:
  token:
    expirationDT: 5M

logging:
  level:
    by:
      attrade:
        controller: DEBUG
        config: DEBUG
        service: DEBUG
    root: ON



#TODO
product:
  search:
    sortFieldsNames:
                - visitors
    sortFieldsTypes:
                - int
    sortReverse:
                - true
    minGramSize: 3
    onFields:
                - name
                - code
                - category.name

#https://developers.facebook.com/apps/542929309886002/fb-login/settings/
#https://theonetechnologies.com/blog/post/how-to-get-facebook-application-id-and-secret-key
facebook:
    client:
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        clientId: 542929309886002
        clientSecret: ${facebookClientSecret}
        tokenName: oauth_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
    resource:
        userInfoUri: https://graph.facebook.com/me

#https://github.com/settings/applications/1171196
#https://github.com/settings/developers
github:
  client:
    clientId: dbcb26787de560f5f9ea
    clientSecret: ${githubClientSecret}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

#https://console.cloud.google.com/apis/credentials?project=attrade-core&supportedpurview=project
google:
    client:
        accessTokenUri: https://www.googleapis.com/oauth2/v4/token
        clientAuthenticationScheme: form
        clientId: 185460716091-1rasqe3vdl56flepchpugq569c4hasnk.apps.googleusercontent.com
        clientSecret: ${googleClientSecret}
        scope: openid,email,profile
        userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    resource:
        preferTokenInfo: true
        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

    #https://script.google.com/d/1zm1fkG5LiHZkp74o5vFzzPLnvnaCt71gCk6fpED51dAfZC9NEKmZMPpx/edit?template=default
    script:
        translator:
          url: https://script.google.com/macros/s/AKfycbxcmiDPFv1OFHdreLBzhHnX5OXt9wW4jctck1KNZsdwwftZScc/exec
security:
    oauth2:
        client:
            auto-approve-scopes: '''.*'''
            client-id: acme
            client-secret: acmesecret
            scope: read,write

oauth2:
  social:
          - google
          - facebook
          - github
  idAttr:
          - sub
          - id
          - id
  nameAttr:
          - email
          - name
          - login

messages-source:
  onlyLanguage: true

picture:
  media:
    init: false
    removeNotSynchronized: true
    compressMain: false
    compressMainQuality: 100
    createMediaPictures: true
    createMarkerPictures: true
    unknownAutoImageType: jpeg
    defaultPictureFileName: default.png

    markerNames:
      - -icon
      - -small

    markerWidths:
      --icon: 110
      --icon576: 60
      --small: 250
      --small576: 110
    paths:
      - /576
    medias:
      - '(max-width: 576px)'
    compressionPercents:
      - 50
    compressionWidths:
      - 250

scheduled:
  CategoryHierarchyService:
    build:
      fixedDelayInMilliseconds: 60000
      initialDelayInMilliseconds: 60000